### ISSUE TITLE
Sample console app won't build

### ISSUE THREAD

**Issue by estrehl** [developerforce/Force.com-Toolkit-for-NET#97] opened 2015-02-20 20:14 UTC
The type or namespace name 'Salesforce' could not be found (are you missing a using directive or an assembly reference?)

This is after downloading from git, opening in VS2012, and restore/update the packages thru NuGet. References are there, packages appear to be downloaded...

Any thoughts as to why it would fail?

**Comment by melih154** [comment] 2015-03-03 19:51
I have the same problem. VS displays below warning. I am using this package on project with .NET Framework 4.

Warning	27	The primary reference "Salesforce.Force" could not be resolved because it has an indirect dependency on the framework assembly "System.Text.Encoding, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" which could not be resolved in the currently targeted framework. ".NETFramework,Version=v4.0". To resolve this problem, either remove the reference "Salesforce.Force" or retarget your application to a framework version which contains "System.Text.Encoding, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".	Imprima.Connect.SalesForceREST

**Comment by v50minasyan** [comment] 2015-03-12 00:28
You are probably running issues with .Net 4.0 - since the API is using Async/Await , .Net 4.0 is not supported. 
Switch to .net 4.5 and you should be able to build

**Comment by estrehl** [comment] 2015-03-12 16:23
@v50minasyan : the project is already set to 4.5. As seen in melih154's post, the issue is that the salesforce.Force and Salesforce.Common included in the repository still apparently are built off the 4.0 framework, at least indirectly: the newtonsoft & threading stuff all seems to be pointed at 4.0. if I go back to the master src, still get issues with different bits or packages pointed at the wrong framework. I've tried half a dozen times now to get everything lined out with no success.

**Comment by tomajar** [comment] 2015-04-15 16:49
Hi, I think the folder structure is a bit odd. I have an issue with build any sample ;)

There is no solution file(s) for the sample projects.  It could work just like that, but please note, that in the .csproj of the sample project the reference to the packages is like:

`..\..\src\packages\`

Because of this structure, the missing solution for sample project should be in the "\src\" folder (you really want to re-use 'packages' folder?) 

Moreover, the samples will not build, if first, you will not try to build the ForceToolkitForNET.sln because it will downolad packages to the \src\packages\ that are required 

Once again - moreover - the sample projects contains a reference to  "\src\ForceToolkitForNET\bin\Debug\Salesforce.Force.dll" ?

Maybe that's another reason why it can't be find?

I really think that the sample projects should rebuild all possible and required dependencies.

The samples builds should work on clean git clone.

**Comment by wadewegner** [comment] 2015-04-15 17:25
Agreed. And if they don't it's a regression. I'll mark this as a bug.

**Comment by wadewegner** [comment] 2015-04-19 00:09
I've fixed the samples here. https://github.com/developerforce/Force.com-Toolkit-for-NET/tree/master/samples

I also included a `build-samples.cmd` script [here](https://github.com/developerforce/Force.com-Toolkit-for-NET/blob/master/scripts/build-samples.cmd) to make it easier to ensure they're building.

**Closed by wadewegner** 2015-04-19 00:09 UTC
Labels: bug
