### ISSUE TITLE
SOQL Like Operator Leading Wildcard % Fails on Integer

### ISSUE THREAD

**Issue by bhardister** [developerforce/Force.com-Toolkit-for-NET#111] opened 2015-04-30 15:33 UTC
When the string searched for in the query starts with a number, this fails to return the correct result:
<b>var test = await client.QueryAsync<TFSCase>("SELECT Id, CaseNumber, TFS__c FROM Case WHERE TFS__c LIKE '%12364Test%'");</b>
The same query from the SF developer console query panel works:
<b>SELECT Id, CaseNumber, TFS__c, TFS_Status__c, Type__c FROM Case WHERE TFS__c LIKE '%12364Test%'</b>
If the c# based query is slightly modified to include an underscore before a number it works:
<b>var test = await client.QueryAsync<TFSCase>("SELECT Id, CaseNumber, TFS__c FROM Case WHERE TFS__c LIKE '%_12364Test%'");</b>
This leads me to think that the toolkit has a bug when passing the value %{any number} such that SF does not see it as a string, or does not see it as %{any number}. I was able to reproduce and confirm this many times.

**Comment by tomajar** [comment] 2015-04-30 18:39
Hi @bhardister 

The problem is probably with url encoding. Some characters needs to be encoded before send in query string, otherwise, they will be miss-interpreted.

In code I can see 

```cs
(string.Format("query?q={0}", Uri.EscapeDataString(query)));
```

The EscapeDataString changes characters like "~/^" to proper 
[http://stackoverflow.com/questions/26309731/why-does-uri-escapedatastring-return-a-different-result-on-my-ci-server-compared]

But the problem is that it doesn't escape %12364Test%.

Why it's a problem?

Because %12 is not un-escaped, and interpreted as some other character.


So @bhardister, what if you try use 

```cs
var encodedQuery = System.Web.HttpUtility.UrlEncode("SELECT Id, CaseNumber, TFS__c FROM Case WHERE TFS__c LIKE '%12364Test%'")

var test = await client.QueryAsync(encodedQuery)
```

This would be similar to query like

> SELECT+Id%2C+CaseNumber%2C+TFS__c+FROM+Case+WHERE+TFS__c+LIKE+%27%2512364Test%25

I'm not sure will this work, because it will be double-encoded (by you, and by library), and even if it works, then you will have to remove your encoding, when the bug will be fixed.

I also don't state, that the System.Web.HttpUtility.UrlEncode is the best fix here, but after all, @wadewegner  needs to use best method, to properly encode url query string parameter (there is no need to encode whole url).

Does this helps?

**Comment by tomajar** [comment] 2015-05-01 10:07
One more thought @bhardister,

please test this:

```cs
var query = "SELECT Id, CaseNumber, TFS__c FROM Case WHERE TFS__c LIKE '%12364Test%'";

// temp hack
query = query.Replace("%","%25");

var test = await client.QueryAsync(query);
```

In theory, this should work in your case too, but it's very ugly, and cannot be considered as library fix.

**Comment by wadewegner** [comment] 2015-08-25 21:41
What do you think of this solution?

```cs
Uri.EscapeUriString(Encoding.UTF8.GetString(Encoding.ASCII.GetBytes("SELECT Id, CaseNumber, TFS__c FROM Case WHERE TFS__c LIKE '%12364Test%'")))
```

I could update the code accordingly.

**Comment by dcarroll** [comment] 2015-08-25 21:44
Why GetBytes, then GetString?

**Comment by wadewegner** [comment] 2015-08-25 22:00
Incidentally, while trying to write a unit test, I used the following:

```cs
const string query = "SELECT Id, Name, Description, AccountNumber FROM Account WHERE AccountNumber LIKE '%9671111%'";
            
var queryResult = await _client.QueryAsync<dynamic>(query);
```

And it seems to work just fine. I don't have your case data to test with. @bhardister can you please review and see if there's something else at play?

**Comment by tomajar** [comment] 2015-08-26 09:27
Hi @wadewegner 

I've no time to look at this now, but please review all your tests.. you cannot use:

```cs
var queryResult = await _client.QueryAsync<dynamic>(query);
```

it will never fail, because you don't wait for async result. I think that your tests are just not working.

please review all your tests and fix like this:

```cs
var queryResult = await _client.QueryAsync<dynamic>(query).Result;
```

just wait for the '.Result' in the tests when executing async.

:)

**Comment by wadewegner** [comment] 2015-08-26 15:14
Your second example is not compilable. You cannot await while synchronously blocking for result.

The unit tests function just fine and definitely fail if not working.

**Comment by wadewegner** [comment] 2015-08-26 16:25
I highly recommending reading this article: <https://msdn.microsoft.com/en-us/magazine/Dn818493.aspx>

A key point from it: "To test an asynchronous method’s behavior, you must observe the task it returns. The best way to do this is to await the task returned from the method under test." The functional/unit tests do in fact await the task returned.

I'd also recommend reading this response from Stephen Clearly about the difference between `await` and `.Result`: <http://stackoverflow.com/a/24657079>

Please let me know if I've misunderstood. I'm always looking forward ways to make the this library work better!

**Comment by wadewegner** [comment] 2015-08-28 20:04
I'm going to close this as norepro for now. Please re-open if appropriate.

**Closed by wadewegner** 2015-08-28 20:04 UTC
Labels: norepro
